name: 'WordPress Plugin/Theme Deployment Action'
description: 'Deploy WordPress plugins or themes from GitHub to a server using SSH and rsync'
branding:
  icon: 'copy'
  color: 'blue'
inputs:
  SSH_PRIVATE_KEY:
    description: 'The private SSH key for server access'
    required: true
  SERVER_HOST:
    description: 'The SSH host of the server'
    required: true
  SERVER_USER:
    description: 'The SSH username'
    required: true
  REMOTE_PATH:
    description: 'The remote path on the server where files should be deployed (e.g., wp-content/plugins/my-plugin)'
    required: true
  REF:
    description: 'The git reference (branch, tag, or commit SHA) to deploy from. Modify the checkout step in your workflow to use this ref.'
    default: ''
  SRC_PATH:
    description: 'Local path to the source files for deployment'
    default: '.'
  FLAGS:
    description: 'Rsync flags'
    default: '-azvrhi --inplace --exclude=.*'
  PHP_LINT:
    description: 'Enable PHP linting'
    default: 'false'
  CACHE_CLEAR:
    description: 'Clear WordPress cache after deployment'
    default: 'false'
  SCRIPT:
    description: 'Post-deploy script to run on the server'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'